# Generated by Django 5.2.9 on 2026-05-12 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_wallettransaction_playergameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Added Funds'), ('WITHDRAWAL', 'Cashed Out'), ('WITHDRAWAL_PENDING', 'Withdrawal Requested'), ('WITHDRAWAL_REJECTED', 'Withdrawal Refunded'), ('ENTRY_FEE', 'Tournament Entry Fee'), ('PRIZE', 'Prize Money Won'), ('REFUND', 'Tournament Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upi_id', models.CharField(help_text="User's upi id for cash transfer", max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected / Refunded')], default='PENDING', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
