# Generated by Django 5.2.9 on 2026-05-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='withdrawal_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='accounts.withdrawalrequest'),
        ),
    ]
