# Generated by Django 5.2.9 on 2026-01-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('main_category', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('action', models.FloatField(blank=True, null=True)),
                ('graphics', models.FloatField(blank=True, null=True)),
                ('story', models.FloatField(blank=True, null=True)),
                ('gameplay', models.FloatField(blank=True, null=True)),
                ('developer', models.CharField(blank=True, max_length=30, null=True)),
                ('publisher', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('trailer_1', models.URLField(blank=True, null=True)),
                ('trailer_2', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='games', to='games.gamecategory')),
            ],
        ),
    ]
