# Generated by Django 5.2.9 on 2026-01-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
