# Generated by Django 5.2.9 on 2026-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_games_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='promo_background',
            field=models.ImageField(blank=True, null=True, upload_to='games/promo_bgs/'),
        ),
    ]
