"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID')

CLOUDFLARE_ACCOUNT_ID = os.getenv('CLOUDFLARE_ACCOUNT_ID')
CLOUDFLARE_API_TOKEN = os.getenv('CLOUDFLARE_API_TOKEN')

RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET')



ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.onrender.com']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',


    # Other installed apps
    'corsheaders',
    'rest_framework',
    'django_filters',
    'rest_framework_simplejwt',
    'djoser',
    



    # Custom apps
    'accounts',
    'games',
    'streams',
    'tournaments',
    'chat',
]


## Make DRF to authenticate only useing JWT Bearer tokens

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}


## Token expiry time

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=20),

    # The rest may remain default
}



## WE USE A CUSTOM EMAIL VERIFICATION TOO SO ADD IT TOO

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend', # THE DEFAULT
    'accounts.authentication.EmailAuthBackend',  # CUSTOM EMAIL AUTHENTICATION BACKEND
]


## We are going to use customized user model
AUTH_USER_MODEL = 'accounts.Account'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]




CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://cloudflare-workers-autoconfig-respawnnation.abhijithms7306.workers.dev",
    "https://respawn-nation-js.vercel.app",
    "https://respawnnation.pages.dev",
]


CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",  # Your JS Frontend
    "http://localhost:5174",  # Your TS Frontend
]




ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'








# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



# Supabase + local django database

# Check if SUPABASE_URL exists in the .env file
if os.getenv('SUPABASE_URL'):
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('SUPABASE_URL'), conn_max_age=600)
    }
else:
    # If no SUPABASE_URL is found, fall back to your existing local Postgres setup
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }





# # Postgresql database

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#     }
# }



# DOMAIN = 'respawnnation.pages.dev'         # React frontend's address
# SITE_NAME = 'Respawn Nation'

DOMAIN = 'localhost:5173'         # React frontend's address
SITE_NAME = 'Respawn Nation'
    



# --- DJOSER CONFIGURATION ---
DJOSER = {
    'LOGIN_FIELD': 'email', # Forces Djoser to use email for login, matching your custom User model
    'USER_CREATE_PASSWORD_RETAIN': False,

   
    # Email Verification Settings
    'SEND_ACTIVATION_EMAIL': True,
    'SEND_CONFIRMATION_EMAIL': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    
    # These point to your REACT frontend routes!
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_URL': 'reset-password/{uid}/{token}',
}

# --- EMAIL SMTP CONFIGURATION ---
# For development, you can use your Gmail account with an "App Password"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')










# Cloudinary storage config

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/



STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = BASE_DIR / 'staticfiles'


## for media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Native static storage + Cloudinary media storage
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



JAZZMIN_SETTINGS = {
    # Title on the login screen
    "site_header": "Respawn Nation",
    
    # Title on the brand (top left)
    "site_brand": "Respawn Admin",
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome back, Commander",
    
    # Copyright on the footer
    "copyright": "Respawn Nation Ltd",

    # The Model used for the global search bar (top right)
    "search_model": "accounts.Account",

    # --- SIDEBAR & ICONS ---
    # This automatically puts these models in the sidebar with icons
    "icons": {
        "users.Account": "fas fa-user-shield", # FontAwesome Icon
        "streams.Stream": "fas fa-video",
        "games.Game": "fas fa-gamepad",
    },
    
    # --- TOP MENU ---
    # Links to put in the top bar
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "/"},
    ],

    # --- UI TWEAKS ---
    "show_sidebar": True,
    "navigation_expanded": True,
    "changeform_format": "horizontal_tabs", # Tabs for long forms!
    
    # Custom CSS/JS (optional, usually not needed)
    "custom_css": None,
    "custom_js": None,
}




# UI TWEAKS (Colors)
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Options: darker, flatly, simplex, spacelab
    # "dark_mode_theme": "darkly", # Optional: if you want dark mode
}




# # Add the below if dark mode is what we wanted

# JAZZMIN_UI_TWEAKS = {
#     "theme": "darkly",  # <--- This activates Dark Mode
#     "dark_mode_theme": "darkly",
# }


