# Generated by Django 5.2.9 on 2026-03-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleRoyaleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('game', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('REGISTRATION', 'Registration Open'), ('GENERATING', 'Generating Brackets'), ('LIVE', 'Live'), ('COMPLETED', 'Completed')], default='REGISTRATION', max_length=20)),
                ('max_players', models.IntegerField(default=32)),
                ('registration_deadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournament')),
            ],
            options={
                'unique_together': {('user', 'tournament')},
            },
        ),
        migrations.CreateModel(
            name='BattleRoyaleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tournaments.battleroyalematch')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FootballMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('GROUP', 'Group Stage'), ('KNOCKOUT', 'Knockout')], max_length=20)),
                ('round_name', models.CharField(max_length=50)),
                ('p1_score', models.IntegerField(blank=True, default=0, null=True)),
                ('p2_score', models.IntegerField(blank=True, default=0, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p1', to='tournaments.participant')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_p2', to='tournaments.participant')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='tournaments.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='football_matches', to='tournaments.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='battleroyalematch',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_matches', to='tournaments.tournament'),
        ),
    ]
