# Generated by Django 5.2.9 on 2026-03-07 10:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='points',
        ),
        migrations.AddField(
            model_name='battleroyaleresult',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.footballmatch'),
        ),
        migrations.AddField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battleroyaleresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='br_results', to='tournaments.participant'),
        ),
        migrations.AlterField(
            model_name='footballmatch',
            name='stage',
            field=models.CharField(choices=[('GROUP', 'Group Stage'), ('KNOCKOUT', 'Knockout Stage')], max_length=20),
        ),
        migrations.CreateModel(
            name='FootballStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('matches_played', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_conceded', models.IntegerField(default=0)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='football_stats', to='tournaments.participant')),
            ],
        ),
    ]
