# Generated by Django 5.2.9 on 2026-03-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_participant_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatch',
            name='match_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
