# Generated by Django 5.2.9 on 2026-03-14 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_footballmatch_match_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footballmatch',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournaments.footballmatch'),
        ),
    ]
