# Generated by Django 5.2.9 on 2026-03-15 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_footballmatch_next_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='runner_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_runner_up', to='tournaments.participant'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments_won', to='tournaments.participant'),
        ),
    ]
