# Generated by Django 5.2.9 on 2026-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournament_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttype',
            name='engine_code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
