# Generated by Django 5.2.9 on 2026-03-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournamenttype_engine_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='custom_banner',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/custom_banner'),
        ),
        migrations.AddField(
            model_name='tournamenttype',
            name='format_overlay',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/overlays'),
        ),
    ]
