# Generated by Django 5.2.9 on 2026-03-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournament_custom_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='game_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
