# Generated by Django 5.2.9 on 2026-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_participant_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='base_prize_pool',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Starting guaranteed prize money', max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Entry fee in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='tournament',
            name='platform_cut_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of fee kept by the platform (e.g., 20.00)', max_digits=5),
        ),
    ]
