# Generated by Django 5.2.9 on 2026-04-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0014_order_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballmatch',
            name='player_1_proof',
            field=models.ImageField(blank=True, null=True, upload_to='matches/proof'),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='player_2_proof',
            field=models.ImageField(blank=True, null=True, upload_to='matches/proof'),
        ),
    ]
