# Generated by Django 5.2.9 on 2026-05-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0015_footballmatch_player_1_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prizes_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
