# Generated by Django 5.2.9 on 2026-05-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0016_tournament_prizes_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroyalematch',
            name='player_1_proof',
            field=models.ImageField(blank=True, null=True, upload_to='br_matches/proof'),
        ),
        migrations.AddField(
            model_name='battleroyalematch',
            name='player_2_proof',
            field=models.ImageField(blank=True, null=True, upload_to='br_matches/proof'),
        ),
    ]
