# Generated by Django 5.2.9 on 2026-05-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0017_battleroyalematch_player_1_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleroyalematch',
            name='player_1_proof',
        ),
        migrations.RemoveField(
            model_name='battleroyalematch',
            name='player_2_proof',
        ),
        migrations.AddField(
            model_name='battleroyaleresult',
            name='screenshot_proof',
            field=models.ImageField(blank=True, null=True, upload_to='br_matches/proof'),
        ),
    ]
