# Generated by Django 5.2.9 on 2026-05-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0018_remove_battleroyalematch_player_1_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='requires_player_proof',
            field=models.BooleanField(default=True, help_text='If True, players must upload screenshots to submit scores.'),
        ),
    ]
