# Generated by Django 5.2.9 on 2026-05-19 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0019_tournament_requires_player_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleroyaleresult',
            old_name='screenshot_proof',
            new_name='group_1_screenshot_proof',
        ),
    ]
