# Generated by Django 5.2.9 on 2026-05-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0020_rename_screenshot_proof_battleroyaleresult_group_1_screenshot_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroyaleresult',
            name='group_2_screenshot_proof',
            field=models.ImageField(blank=True, null=True, upload_to='br_matches/proof'),
        ),
    ]
