# Generated by Django 5.2.9 on 2026-05-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0021_battleroyaleresult_group_2_screenshot_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleroyaleresult',
            old_name='group_1_screenshot_proof',
            new_name='screenshot_proof',
        ),
        migrations.RemoveField(
            model_name='battleroyaleresult',
            name='group_2_screenshot_proof',
        ),
        migrations.AddField(
            model_name='battleroyalematch',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Notes on lobby restarts or room keys', null=True),
        ),
        migrations.AddField(
            model_name='battleroyalematch',
            name='deadline_time',
            field=models.DateTimeField(blank=True, help_text='Deadline for scores to be final', null=True),
        ),
        migrations.AddField(
            model_name='battleroyalematch',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='Time the custom room lobby opens', null=True),
        ),
        migrations.AddField(
            model_name='battleroyalematch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting / Brackets Not Set'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('AWAITING_REVIEW', 'Awaiting Review'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Reason for resolving a dispute or forfeit', null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='deadline_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Waiting / Brackets Not Set'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('AWAITING_REVIEW', 'Awaiting Review'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='footballmatch',
            name='win_reason',
            field=models.CharField(blank=True, choices=[('SCORE', 'Normal Win by Score'), ('FORFEIT', 'Opponent Forfeited / No Show'), ('DISQUALIFIED', 'Opponent Disqualified')], max_length=20, null=True),
        ),
    ]
