# Generated by Django 5.2.9 on 2026-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0022_rename_group_1_screenshot_proof_battleroyaleresult_screenshot_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenttype',
            name='engine_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PointsRaceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.IntegerField(default=1)),
                ('p1_score', models.IntegerField(default=0)),
                ('p2_score', models.IntegerField(default=0)),
                ('player_1_proof', models.ImageField(blank=True, null=True, upload_to='points_race/proof')),
                ('player_2_proof', models.ImageField(blank=True, null=True, upload_to='points_race/proof')),
                ('status', models.CharField(choices=[('PENDING', 'Waiting / Brackets Not Set'), ('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('AWAITING_REVIEW', 'Awaiting Review'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('player_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_matches_as_p1', to='tournaments.participant')),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_matches_as_p2', to='tournaments.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_race_matches', to='tournaments.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_matches_won', to='tournaments.participant')),
            ],
        ),
        migrations.CreateModel(
            name='PointsRaceStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('matches_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_race_stats', to='tournaments.participant')),
            ],
        ),
    ]
