# Generated by Django 5.2.9 on 2026-06-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
        ('tournaments', '0022_rename_group_1_screenshot_proof_battleroyaleresult_screenshot_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='active_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streams', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='stream',
            name='external_url',
            field=models.URLField(blank=True, help_text='Used for Twitch or YouTube links', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_type',
            field=models.CharField(choices=[('CLOUDFLARE', 'Cloudflare Live'), ('YOUTUBE', 'YouTube Live'), ('TWITCH', 'Twitch')], default='CLOUDFLARE', max_length=20),
        ),
    ]
