# Generated by Django 5.2.9 on 2026-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_stream_active_tournament_stream_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='streams/thumbnails/'),
        ),
    ]
